BoidsController:
  address: "boids/BoidsController"
  ros_name_space: "boids"

  required_data:
    self_data: ['hector_map', 'laser_scan']
    neighbor_data: []

  neighbor_localization: 'shared_gps'
  # neighbor_localization: 'uvdar'
  control_type: 'velocity'

controller_names: ['BoidsController']

initial_controller: 'BoidsController'
