uav_radius: 1.0
lidar_range: 10
takeoff_height: 2.5
sigma_occlusion: 0.1

flock_safety_rad: 4.0
obst_f_max_dist: 1.5
obst_f_const: 1.0
k_nav: 1.2
invalidate_time: 1.0
path_invalidate_time: 4.0

path_in: "path_finder/path"
mrs_uav_status_out: "mrs_uav_status/display_string"
set_path_fndr: "path_finder/path_goto"
set_goal: "pacnav_controller/goto"
